In [ ]:
###Hailey Traina
###Homework 4
###September 17, 2023

In [ ]:
Problem 1. We have a body of mass m (kg). When a net force, F in newtons (N) acts on it, according to Newton’s second law, the body will get an acceleration a (m/s2).

Remember that F = ma
Write an expression that calculates F s:
    

In [1]:
import numpy as np

In [2]:
def force_to_acceleration(m, F):
    ##creating a function to calculate acceleration from mass and force
    ## a = F/m
    a = F/m
    return a
print("Problem 1:")
print(force_to_acceleration(150, 100))
print(force_to_acceleration(150,22))
print(force_to_acceleration(150,450))

Problem 1:
0.6666666666666666
0.14666666666666667
3.0


In [7]:
print("Problem 2:")
import acceleration as acc


Problem 2:


In [12]:
print(acc.acceleration(10,13,0,2))
print(acc.acceleration(15,30,10,14))
print(acc.acceleration(32,36,14,16))
print(acc.acceleration(42,20,28,32)) 
print(acc.acceleration(20,22,0,10))
##checked code on a calculator and on another website to confirm accelerations!
##used this website: https://www.omnicalculator.com/physics/acceleration

1.5
3.75
2.0
-5.5
0.2


In [14]:
print("Problem 3:")
first_list = np.arange(0,101,10)
print(first_list)
second_list = np.arange(0,1001,100)
print(second_list)
print(second_list[3:5], second_list[8])
print("The first is:", acc.acceleration(first_list[3], first_list[4], second_list[3], second_list[4]))
print("The second is:", acc.acceleration(first_list[4], first_list[5], second_list[4], second_list[5]))
print("The third is:", acc.acceleration(first_list[5], first_list[8], second_list[5], second_list[8]))
first_list[5] = 90
print(first_list)
print("The fourth is:", acc.acceleration(first_list[5], first_list[8], second_list[5], second_list[8]))
##it does work, however, this acceleration is negative! This means with this pair of velocities, the fourth is de-accerlerating

Problem 3:
[  0  10  20  30  40  50  60  70  80  90 100]
[   0  100  200  300  400  500  600  700  800  900 1000]
[300 400] 800
The first is: 0.1
The second is: 0.1
The third is: 0.1
[  0  10  20  30  40  90  60  70  80  90 100]
The fourth is: -0.03333333333333333
